services:
  db:
    image: "postgres:16"
    environment:
      POSTGRES_PASSWORD: "pw"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5432/ || exit 1"]
      interval: 2s
      timeout: 1s
      retries: 5
volumes:
  pgdata: {}
