### YamlMime:ManagedReference
items:
- uid: Sora.Core.Infrastructure.Constants.Configuration.Env
  commentId: T:Sora.Core.Infrastructure.Constants.Configuration.Env
  id: Constants.Configuration.Env
  parent: Sora.Core.Infrastructure
  children:
  - Sora.Core.Infrastructure.Constants.Configuration.Env.AspNetCoreEnvironment
  - Sora.Core.Infrastructure.Constants.Configuration.Env.Ci
  - Sora.Core.Infrastructure.Constants.Configuration.Env.DotnetEnvironment
  - Sora.Core.Infrastructure.Constants.Configuration.Env.DotnetRunningInContainer
  - Sora.Core.Infrastructure.Constants.Configuration.Env.KubernetesServiceHost
  - Sora.Core.Infrastructure.Constants.Configuration.Env.TfBuild
  langs:
  - csharp
  - vb
  name: Constants.Configuration.Env
  nameWithType: Constants.Configuration.Env
  fullName: Sora.Core.Infrastructure.Constants.Configuration.Env
  type: Class
  source:
    remote:
      path: src/Sora.Core/Infrastructure/Constants.cs
      branch: dev
      repo: https://github.com/sylin-labs/sora-framework.git
    id: Env
    path: ../../src/Sora.Core/Infrastructure/Constants.cs
    startLine: 29
  assemblies:
  - Sora.Core
  namespace: Sora.Core.Infrastructure
  syntax:
    content: public static class Constants.Configuration.Env
    content.vb: Public Module Constants.Configuration.Env
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Sora.Core.Infrastructure.Constants.Configuration.Env.DotnetEnvironment
  commentId: F:Sora.Core.Infrastructure.Constants.Configuration.Env.DotnetEnvironment
  id: DotnetEnvironment
  parent: Sora.Core.Infrastructure.Constants.Configuration.Env
  langs:
  - csharp
  - vb
  name: DotnetEnvironment
  nameWithType: Constants.Configuration.Env.DotnetEnvironment
  fullName: Sora.Core.Infrastructure.Constants.Configuration.Env.DotnetEnvironment
  type: Field
  source:
    remote:
      path: src/Sora.Core/Infrastructure/Constants.cs
      branch: dev
      repo: https://github.com/sylin-labs/sora-framework.git
    id: DotnetEnvironment
    path: ../../src/Sora.Core/Infrastructure/Constants.cs
    startLine: 31
  assemblies:
  - Sora.Core
  namespace: Sora.Core.Infrastructure
  syntax:
    content: public const string DotnetEnvironment = "DOTNET:ENVIRONMENT"
    return:
      type: System.String
    content.vb: Public Const DotnetEnvironment As String = "DOTNET:ENVIRONMENT"
- uid: Sora.Core.Infrastructure.Constants.Configuration.Env.AspNetCoreEnvironment
  commentId: F:Sora.Core.Infrastructure.Constants.Configuration.Env.AspNetCoreEnvironment
  id: AspNetCoreEnvironment
  parent: Sora.Core.Infrastructure.Constants.Configuration.Env
  langs:
  - csharp
  - vb
  name: AspNetCoreEnvironment
  nameWithType: Constants.Configuration.Env.AspNetCoreEnvironment
  fullName: Sora.Core.Infrastructure.Constants.Configuration.Env.AspNetCoreEnvironment
  type: Field
  source:
    remote:
      path: src/Sora.Core/Infrastructure/Constants.cs
      branch: dev
      repo: https://github.com/sylin-labs/sora-framework.git
    id: AspNetCoreEnvironment
    path: ../../src/Sora.Core/Infrastructure/Constants.cs
    startLine: 32
  assemblies:
  - Sora.Core
  namespace: Sora.Core.Infrastructure
  syntax:
    content: public const string AspNetCoreEnvironment = "ASPNETCORE:ENVIRONMENT"
    return:
      type: System.String
    content.vb: Public Const AspNetCoreEnvironment As String = "ASPNETCORE:ENVIRONMENT"
- uid: Sora.Core.Infrastructure.Constants.Configuration.Env.DotnetRunningInContainer
  commentId: F:Sora.Core.Infrastructure.Constants.Configuration.Env.DotnetRunningInContainer
  id: DotnetRunningInContainer
  parent: Sora.Core.Infrastructure.Constants.Configuration.Env
  langs:
  - csharp
  - vb
  name: DotnetRunningInContainer
  nameWithType: Constants.Configuration.Env.DotnetRunningInContainer
  fullName: Sora.Core.Infrastructure.Constants.Configuration.Env.DotnetRunningInContainer
  type: Field
  source:
    remote:
      path: src/Sora.Core/Infrastructure/Constants.cs
      branch: dev
      repo: https://github.com/sylin-labs/sora-framework.git
    id: DotnetRunningInContainer
    path: ../../src/Sora.Core/Infrastructure/Constants.cs
    startLine: 33
  assemblies:
  - Sora.Core
  namespace: Sora.Core.Infrastructure
  syntax:
    content: public const string DotnetRunningInContainer = "DOTNET:RUNNING:IN:CONTAINER"
    return:
      type: System.String
    content.vb: Public Const DotnetRunningInContainer As String = "DOTNET:RUNNING:IN:CONTAINER"
- uid: Sora.Core.Infrastructure.Constants.Configuration.Env.KubernetesServiceHost
  commentId: F:Sora.Core.Infrastructure.Constants.Configuration.Env.KubernetesServiceHost
  id: KubernetesServiceHost
  parent: Sora.Core.Infrastructure.Constants.Configuration.Env
  langs:
  - csharp
  - vb
  name: KubernetesServiceHost
  nameWithType: Constants.Configuration.Env.KubernetesServiceHost
  fullName: Sora.Core.Infrastructure.Constants.Configuration.Env.KubernetesServiceHost
  type: Field
  source:
    remote:
      path: src/Sora.Core/Infrastructure/Constants.cs
      branch: dev
      repo: https://github.com/sylin-labs/sora-framework.git
    id: KubernetesServiceHost
    path: ../../src/Sora.Core/Infrastructure/Constants.cs
    startLine: 34
  assemblies:
  - Sora.Core
  namespace: Sora.Core.Infrastructure
  syntax:
    content: public const string KubernetesServiceHost = "KUBERNETES:SERVICE:HOST"
    return:
      type: System.String
    content.vb: Public Const KubernetesServiceHost As String = "KUBERNETES:SERVICE:HOST"
- uid: Sora.Core.Infrastructure.Constants.Configuration.Env.Ci
  commentId: F:Sora.Core.Infrastructure.Constants.Configuration.Env.Ci
  id: Ci
  parent: Sora.Core.Infrastructure.Constants.Configuration.Env
  langs:
  - csharp
  - vb
  name: Ci
  nameWithType: Constants.Configuration.Env.Ci
  fullName: Sora.Core.Infrastructure.Constants.Configuration.Env.Ci
  type: Field
  source:
    remote:
      path: src/Sora.Core/Infrastructure/Constants.cs
      branch: dev
      repo: https://github.com/sylin-labs/sora-framework.git
    id: Ci
    path: ../../src/Sora.Core/Infrastructure/Constants.cs
    startLine: 35
  assemblies:
  - Sora.Core
  namespace: Sora.Core.Infrastructure
  syntax:
    content: public const string Ci = "CI"
    return:
      type: System.String
    content.vb: Public Const Ci As String = "CI"
- uid: Sora.Core.Infrastructure.Constants.Configuration.Env.TfBuild
  commentId: F:Sora.Core.Infrastructure.Constants.Configuration.Env.TfBuild
  id: TfBuild
  parent: Sora.Core.Infrastructure.Constants.Configuration.Env
  langs:
  - csharp
  - vb
  name: TfBuild
  nameWithType: Constants.Configuration.Env.TfBuild
  fullName: Sora.Core.Infrastructure.Constants.Configuration.Env.TfBuild
  type: Field
  source:
    remote:
      path: src/Sora.Core/Infrastructure/Constants.cs
      branch: dev
      repo: https://github.com/sylin-labs/sora-framework.git
    id: TfBuild
    path: ../../src/Sora.Core/Infrastructure/Constants.cs
    startLine: 36
  assemblies:
  - Sora.Core
  namespace: Sora.Core.Infrastructure
  syntax:
    content: public const string TfBuild = "TF:BUILD"
    return:
      type: System.String
    content.vb: Public Const TfBuild As String = "TF:BUILD"
references:
- uid: Sora.Core.Infrastructure
  commentId: N:Sora.Core.Infrastructure
  href: Sora.html
  name: Sora.Core.Infrastructure
  nameWithType: Sora.Core.Infrastructure
  fullName: Sora.Core.Infrastructure
  spec.csharp:
  - uid: Sora
    name: Sora
    href: Sora.html
  - name: .
  - uid: Sora.Core
    name: Core
    href: Sora.Core.html
  - name: .
  - uid: Sora.Core.Infrastructure
    name: Infrastructure
    href: Sora.Core.Infrastructure.html
  spec.vb:
  - uid: Sora
    name: Sora
    href: Sora.html
  - name: .
  - uid: Sora.Core
    name: Core
    href: Sora.Core.html
  - name: .
  - uid: Sora.Core.Infrastructure
    name: Infrastructure
    href: Sora.Core.Infrastructure.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
