### YamlMime:ManagedReference
items:
- uid: Sora.Data.Core.Configuration
  commentId: N:Sora.Data.Core.Configuration
  id: Sora.Data.Core.Configuration
  children:
  - Sora.Data.Core.Configuration.AggregateBags
  - Sora.Data.Core.Configuration.IDataConnectionResolver
  - Sora.Data.Core.Configuration.StorageNameRegistry
  langs:
  - csharp
  - vb
  name: Sora.Data.Core.Configuration
  nameWithType: Sora.Data.Core.Configuration
  fullName: Sora.Data.Core.Configuration
  type: Namespace
  assemblies:
  - Sora.Data.Core
references:
- uid: Sora.Data.Core.Configuration.IDataConnectionResolver
  commentId: T:Sora.Data.Core.Configuration.IDataConnectionResolver
  href: Sora.Data.Core.Configuration.IDataConnectionResolver.html
  name: IDataConnectionResolver
  nameWithType: IDataConnectionResolver
  fullName: Sora.Data.Core.Configuration.IDataConnectionResolver
- uid: Sora.Data.Core.Configuration.StorageNameRegistry
  commentId: T:Sora.Data.Core.Configuration.StorageNameRegistry
  href: Sora.Data.Core.Configuration.StorageNameRegistry.html
  name: StorageNameRegistry
  nameWithType: StorageNameRegistry
  fullName: Sora.Data.Core.Configuration.StorageNameRegistry
- uid: Sora.Data.Core.Configuration.AggregateBags
  commentId: T:Sora.Data.Core.Configuration.AggregateBags
  href: Sora.Data.Core.Configuration.AggregateBags.html
  name: AggregateBags
  nameWithType: AggregateBags
  fullName: Sora.Data.Core.Configuration.AggregateBags
