### YamlMime:ManagedReference
items:
- uid: Sora.Web.Swagger.Initialization
  commentId: N:Sora.Web.Swagger.Initialization
  id: Sora.Web.Swagger.Initialization
  children:
  - Sora.Web.Swagger.Initialization.SoraAutoRegistrar
  langs:
  - csharp
  - vb
  name: Sora.Web.Swagger.Initialization
  nameWithType: Sora.Web.Swagger.Initialization
  fullName: Sora.Web.Swagger.Initialization
  type: Namespace
  assemblies:
  - Sora.Web.Swagger
references:
- uid: Sora.Web.Swagger.Initialization.SoraAutoRegistrar
  commentId: T:Sora.Web.Swagger.Initialization.SoraAutoRegistrar
  href: Sora.Web.Swagger.Initialization.SoraAutoRegistrar.html
  name: SoraAutoRegistrar
  nameWithType: SoraAutoRegistrar
  fullName: Sora.Web.Swagger.Initialization.SoraAutoRegistrar
