### YamlMime:ManagedReference
items:
- uid: Sora.Web.Swagger
  commentId: N:Sora.Web.Swagger
  id: Sora.Web.Swagger
  children:
  - Sora.Web.Swagger.AddSoraSwaggerExtensions
  - Sora.Web.Swagger.SoraHeadersOperationFilter
  - Sora.Web.Swagger.SoraWebSwaggerOptions
  langs:
  - csharp
  - vb
  name: Sora.Web.Swagger
  nameWithType: Sora.Web.Swagger
  fullName: Sora.Web.Swagger
  type: Namespace
  assemblies:
  - Sora.Web.Swagger
references:
- uid: Sora.Web.Swagger.AddSoraSwaggerExtensions
  commentId: T:Sora.Web.Swagger.AddSoraSwaggerExtensions
  href: Sora.Web.Swagger.AddSoraSwaggerExtensions.html
  name: AddSoraSwaggerExtensions
  nameWithType: AddSoraSwaggerExtensions
  fullName: Sora.Web.Swagger.AddSoraSwaggerExtensions
- uid: Sora.Web.Swagger.SoraHeadersOperationFilter
  commentId: T:Sora.Web.Swagger.SoraHeadersOperationFilter
  href: Sora.Web.Swagger.SoraHeadersOperationFilter.html
  name: SoraHeadersOperationFilter
  nameWithType: SoraHeadersOperationFilter
  fullName: Sora.Web.Swagger.SoraHeadersOperationFilter
- uid: Sora.Web.Swagger.SoraWebSwaggerOptions
  commentId: T:Sora.Web.Swagger.SoraWebSwaggerOptions
  href: Sora.Web.Swagger.SoraWebSwaggerOptions.html
  name: SoraWebSwaggerOptions
  nameWithType: SoraWebSwaggerOptions
  fullName: Sora.Web.Swagger.SoraWebSwaggerOptions
