### YamlMime:ManagedReference
items:
- uid: Sora.Web.Swagger.Infrastructure
  commentId: N:Sora.Web.Swagger.Infrastructure
  id: Sora.Web.Swagger.Infrastructure
  children:
  - Sora.Web.Swagger.Infrastructure.Constants
  - Sora.Web.Swagger.Infrastructure.Constants.Configuration
  langs:
  - csharp
  - vb
  name: Sora.Web.Swagger.Infrastructure
  nameWithType: Sora.Web.Swagger.Infrastructure
  fullName: Sora.Web.Swagger.Infrastructure
  type: Namespace
  assemblies:
  - Sora.Web.Swagger
references:
- uid: Sora.Web.Swagger.Infrastructure.Constants
  commentId: T:Sora.Web.Swagger.Infrastructure.Constants
  href: Sora.Web.Swagger.Infrastructure.Constants.html
  name: Constants
  nameWithType: Constants
  fullName: Sora.Web.Swagger.Infrastructure.Constants
- uid: Sora.Web.Swagger.Infrastructure.Constants.Configuration
  commentId: T:Sora.Web.Swagger.Infrastructure.Constants.Configuration
  href: Sora.Web.Swagger.Infrastructure.Constants.html
  name: Constants.Configuration
  nameWithType: Constants.Configuration
  fullName: Sora.Web.Swagger.Infrastructure.Constants.Configuration
  spec.csharp:
  - uid: Sora.Web.Swagger.Infrastructure.Constants
    name: Constants
    href: Sora.Web.Swagger.Infrastructure.Constants.html
  - name: .
  - uid: Sora.Web.Swagger.Infrastructure.Constants.Configuration
    name: Configuration
    href: Sora.Web.Swagger.Infrastructure.Constants.Configuration.html
  spec.vb:
  - uid: Sora.Web.Swagger.Infrastructure.Constants
    name: Constants
    href: Sora.Web.Swagger.Infrastructure.Constants.html
  - name: .
  - uid: Sora.Web.Swagger.Infrastructure.Constants.Configuration
    name: Configuration
    href: Sora.Web.Swagger.Infrastructure.Constants.Configuration.html
