services:
  api:
    image: "sora-s5.recs:dev"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      Sora__Data__Mongo__ConnectionString: "mongodb://mongo:27017"
      Sora__Data__Mongo__Database: "sora"
      Sora__Ai__AutoDiscoveryEnabled: "true"
      Sora__Ai__AllowDiscoveryInNonDev: "true"
      SORA_AI_OLLAMA_URLS: "http://ollama:11434"
      Sora__Data__Weaviate__Endpoint: "http://weaviate:8080"
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_started
      ollama:
        condition: service_healthy
      weaviate:
        condition: service_healthy
  mongo:
    image: "mongo:7"
    ports:
      - "27018:27017"
    volumes:
      - ./Data/mongo:/data/db
  ollama:
    image: "ollama/ollama:latest"
    ports:
      - "11434:11434"
    volumes:
      - ./Data/ollama:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://ollama:11434/api/tags || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 12
  weaviate:
    image: "semitechnologies/weaviate:1.25.6"
    environment:
      QUERY_DEFAULTS_LIMIT: "25"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "node1"
      RAFT_BOOTSTRAP_EXPECT: "1"
    ports:
      - "8081:8080"
    volumes:
      - ./Data/weaviate:/var/lib/weaviate
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://weaviate:8080/v1/.well-known/ready || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 12
