name: docs-build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install DocFX
        shell: pwsh
        run: |
          dotnet tool update -g docfx || dotnet tool install -g docfx

      - name: Build Docs to resources/website/docs
        shell: pwsh
        working-directory: docs/api
        run: |
          $docfx = Join-Path $env:USERPROFILE '.dotnet/tools/docfx.exe'
          if (-not (Test-Path $docfx)) { $docfx = 'docfx' }
          & $docfx build --serve false
