name: S2 Compose smoke

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  compose-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compose up (API + Mongo + Client)
        working-directory: samples/S2.Compose
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Wait for API readiness
        run: |
          for i in {1..30}; do
            if curl -fsS http://localhost:5054/api/health >/dev/null; then exit 0; fi
            sleep 2
          done
          echo "API did not become ready in time" >&2
          docker compose -f samples/S2.Compose/docker-compose.yml logs --no-color || true
          exit 1

      - name: Probe API basic flows
        run: |
          curl -fsS -X POST http://localhost:5054/api/items -H 'Content-Type: application/json' -d '{"name":"probe"}'
          curl -fsS -X POST http://localhost:5054/api/items/seed/2 -H 'Content-Type: application/json' -d '{}'
          curl -fsS -X DELETE http://localhost:5054/api/items/clear
          curl -fsS http://localhost:5054/api/items | head -c 200

      - name: Compose down
        if: always()
        working-directory: samples/S2.Compose
        run: docker compose -f docker-compose.yml down -v
